### PR TITLE
Updating menu for admin and users.

### PR DESCRIPTION
**Pull request by awalashfaqul**
Updated menu for admin and users.
Updated menu and command instructions for "view accounts and balances", "deposit".

### CODE REVIEW

**Review by NpcRP — APPROVED** [review]
Nicely done, alot of work done.

**Review by suhagan — APPROVED** [review]
The application looks great. Can be merged with the main.

**Review by NpcRP — APPROVED** [review]

**Review by NpcRP — APPROVED** [review]

**Comment by suhagan** [comment]
looking great, can be merged in the main branch.

**Review by suhagan — APPROVED** [review]
Looking Great. Can be added to main branch.

**Pull request closed without merging**
